import type { MenuData, StyleTemplate } from "@/types/menu";

export const mockExtractedMenu: MenuData = {
  restaurant_name: "Al Mahara",
  sections: [
    {
      name: "Appetizers",
      name_ar: "\u0645\u0642\u0628\u0644\u0627\u062a",
      items: [
        {
          name: "Hummus",
          name_ar: "\u062d\u0645\u0635",
          description: "Classic chickpea dip with tahini and olive oil",
          price: 35,
          currency: "AED",
          is_vegetarian: true,
          is_vegan: true,
          is_halal: true,
        },
        {
          name: "Fattoush Salad",
          name_ar: "\u0641\u062a\u0648\u0634",
          description: "Fresh mixed greens with crispy pita, sumac dressing",
          price: 40,
          currency: "AED",
          is_vegetarian: true,
          is_halal: true,
        },
        {
          name: "Lamb Kibbeh",
          name_ar: "\u0643\u0628\u0629",
          description: "Crispy bulgur shells filled with spiced lamb and pine nuts",
          price: 55,
          currency: "AED",
          is_halal: true,
        },
      ],
    },
    {
      name: "Main Courses",
      name_ar: "\u0627\u0644\u0623\u0637\u0628\u0627\u0642 \u0627\u0644\u0631\u0626\u064a\u0633\u064a\u0629",
      items: [
        {
          name: "Grilled Hammour",
          name_ar: "\u0647\u0627\u0645\u0648\u0631 \u0645\u0634\u0648\u064a",
          description: "Local grouper fillet with saffron rice and grilled vegetables",
          price: 120,
          currency: "AED",
          is_halal: true,
        },
        {
          name: "Lamb Ouzi",
          name_ar: "\u0623\u0648\u0632\u064a \u0644\u062d\u0645",
          description: "Slow-roasted lamb shoulder with spiced rice and nuts",
          price: 145,
          currency: "AED",
          is_halal: true,
        },
        {
          name: "Mixed Grill",
          name_ar: "\u0645\u0634\u0627\u0648\u064a \u0645\u0634\u0643\u0644\u0629",
          description: "Selection of lamb chops, chicken shish, and kofta with bread",
          price: 165,
          currency: "AED",
          is_halal: true,
        },
      ],
    },
    {
      name: "Desserts",
      name_ar: "\u062d\u0644\u0648\u064a\u0627\u062a",
      items: [
        {
          name: "Kunafa",
          name_ar: "\u0643\u0646\u0627\u0641\u0629",
          description: "Crispy semolina pastry with sweet cheese and rose syrup",
          price: 45,
          currency: "AED",
          is_vegetarian: true,
          is_halal: true,
        },
        {
          name: "Um Ali",
          name_ar: "\u0623\u0645 \u0639\u0644\u064a",
          description: "Egyptian bread pudding with cream, nuts, and raisins",
          price: 40,
          currency: "AED",
          is_vegetarian: true,
          is_halal: true,
        },
      ],
    },
  ],
};

export const mockTemplates: StyleTemplate[] = [
  {
    id: "1",
    name: "Fine Dining",
    slug: "fine-dining",
    description: "Elegant and sophisticated, perfect for high-end restaurants",
    category: "fine_dining",
    preview_url: null,
    color_scheme: { primary: "#1a1a2e", secondary: "#c9a96e", background: "#fdf6ec" },
    font_config: { heading: "Playfair Display", body: "Inter", arabic: "Amiri" },
    supports_rtl: true,
    example_images: null,
    base_prompt_context: null,
  },
  {
    id: "2",
    name: "Modern Cafe",
    slug: "modern-cafe",
    description: "Clean and minimal, great for cafes and bistros",
    category: "cafe",
    preview_url: null,
    color_scheme: { primary: "#2d3436", secondary: "#00b894", background: "#ffffff" },
    font_config: { heading: "Inter", body: "Inter", arabic: "Amiri" },
    supports_rtl: true,
    example_images: null,
    base_prompt_context: null,
  },
  {
    id: "3",
    name: "Casual Dining",
    slug: "casual-dining",
    description: "Warm and inviting, ideal for family restaurants",
    category: "casual",
    preview_url: null,
    color_scheme: { primary: "#2c1810", secondary: "#d4a574", background: "#fef9f0" },
    font_config: { heading: "Playfair Display", body: "Inter", arabic: "Amiri" },
    supports_rtl: true,
    example_images: null,
    base_prompt_context: null,
  },
  {
    id: "4",
    name: "Fast Food",
    slug: "fast-food",
    description: "Bold and energetic, perfect for quick-service restaurants",
    category: "fast_food",
    preview_url: null,
    color_scheme: { primary: "#e74c3c", secondary: "#f39c12", background: "#ffffff" },
    font_config: { heading: "Inter", body: "Inter", arabic: "Amiri" },
    supports_rtl: false,
    example_images: null,
    base_prompt_context: null,
  },
];
